'use client';
import { useFieldArray, useForm, type FieldErrors } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { AlertCircle, Plus, Trash2, ChevronDown, Save } from 'lucide-react';
import { Brand } from '@/components/brand'; import { Button, Card, Input, Label, Textarea } from '@/components/ui'; import { Protected } from '@/components/protected'; import { DatePicker } from '@/components/date-picker'; import { NativeSelect } from '@/components/base-ui/native-select';
import { cleanEventForm, eventFormSchema, type EventFormValues as FormValues } from '@/lib/event-form';
import { invalidateEventsCache } from '@/hooks/use-events';

const actionOptions = [{ value: 'Follow up', label: 'Follow-up' }, { value: 'Send CP', label: 'Kirim profil perusahaan' }, { value: 'Send Catalog', label: 'Kirim katalog' }, { value: 'Contact PIC', label: 'Hubungi PIC' }, { value: 'Schedule Meeting', label: 'Jadwalkan pertemuan' }];
const blankPerson = { name: '', company: '', position: '', contact: '', social: '', chatSummary: '', potential: '', followUp: false }; const blankProspect = { companyName: '', industry: '', personMet: '', potentialSummary: '', notes: '' };

function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <div><Label>{label}</Label>{children}{error && <p className="mt-1 text-xs text-red-600">{error}</p>}</div>; }
function Collapsible({ title, index, onRemove, forceOpenSignal, children }: { title: string; index: number; onRemove: () => void; forceOpenSignal: number; children: React.ReactNode }) { const [open, setOpen] = useState(index === 0); useEffect(() => { if (forceOpenSignal > 0) setOpen(true); }, [forceOpenSignal]); return <Card className="overflow-hidden"><div className="flex items-center gap-2 p-3"><button type="button" onClick={() => setOpen(!open)} className="flex min-h-11 flex-1 items-center gap-3 text-left"><span className="grid h-7 w-7 place-items-center rounded-lg bg-mist text-xs font-bold text-leaf">{index + 1}</span><span className="truncate text-sm font-semibold">{title}</span><ChevronDown size={17} className={`ml-auto transition ${open ? 'rotate-180' : ''}`}/></button><button type="button" onClick={onRemove} className="grid h-11 w-11 place-items-center rounded-xl text-slate-400 hover:bg-red-50 hover:text-red-600" aria-label={`Hapus ${title}`}><Trash2 size={17}/></button></div>{open && <div className="grid gap-4 border-t border-line p-4">{children}</div>}</Card>; }

function collectErrorMessages(value: unknown, messages: string[] = []): string[] { if (!value || typeof value !== 'object') return messages; if ('message' in value && typeof value.message === 'string') messages.push(value.message); else Object.entries(value).forEach(([key, child]) => { if (key !== 'ref' && key !== 'types') collectErrorMessages(child, messages); }); return Array.from(new Set(messages)); }

export default function FormPage() { const router = useRouter(); const [status, setStatus] = useState(''); const [expandSignal, setExpandSignal] = useState(0); const [editId, setEditId] = useState<number | null>(null); const [loadingEdit, setLoadingEdit] = useState(true); const { register, control, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(eventFormSchema), mode: 'onChange', reValidateMode: 'onChange', shouldFocusError: true, defaultValues: { name: '', date: '', location: '', organizer: '', type: '', networking: [], prospects: [], nextActions: [], generalNotes: '' } }); const people = useFieldArray({ control, name: 'networking' }); const prospectItems = useFieldArray({ control, name: 'prospects' });
  useEffect(() => { const value = new URLSearchParams(window.location.search).get('edit'); const id = value ? Number(value) : null; if (!id || !Number.isInteger(id)) { setLoadingEdit(false); return; } setEditId(id); fetch('/api/events', { credentials: 'include', cache: 'no-store' }).then(response => response.ok ? response.json() : Promise.reject()).then((items: Array<any>) => { const event = items.find(item => item.id === id); if (!event) throw new Error(); reset({ name: event.name, date: event.date, location: event.location, organizer: event.organizer, type: event.type, networking: event.networking.map((person: any) => ({ name: person.name, company: person.company, position: person.position, contact: person.contact, social: person.social, chatSummary: person.chatSummary, potential: person.potential, followUp: person.followUp })), prospects: event.prospects.map((prospect: any) => ({ companyName: prospect.companyName, industry: prospect.industry, personMet: prospect.personMet, potentialSummary: prospect.potentialSummary, notes: prospect.notes })), nextActions: event.nextActions, generalNotes: event.generalNotes }); }).catch(() => setStatus('Catatan yang akan diedit tidak dapat dimuat.')).finally(() => setLoadingEdit(false)); }, [reset]);
  async function submit(data: FormValues) { setStatus(''); try { const cleaned = cleanEventForm(data); const response = await fetch('/api/events', { method: editId ? 'PATCH' : 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editId ? { id: editId, ...cleaned } : cleaned) }); const result = await response.json().catch(() => null); if (response.ok) { invalidateEventsCache(); router.push('/success'); router.refresh(); return; } setStatus(result?.error === 'Akses tidak sah' ? 'Sesi akses habis. Silakan kembali ke halaman PIN.' : result?.error === 'Database belum dikonfigurasi' ? 'Database belum terhubung.' : result?.error === 'Validasi gagal' ? 'Data ditolak server. Periksa kembali kolom wajib.' : result?.error || 'Catatan gagal disimpan. Coba lagi.'); } catch { setStatus('Tidak dapat terhubung ke server. Periksa koneksi lalu coba lagi.'); } }
  function invalid(formErrors: FieldErrors<FormValues>) { const messages = collectErrorMessages(formErrors); setStatus(`Lengkapi formulir: ${messages.join(' • ') || 'periksa kolom yang ditandai merah.'}`); setExpandSignal(signal => signal + 1); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  return <Protected><Brand/><main className="mx-auto max-w-3xl px-4 pb-40 sm:pb-12 animate-page-enter"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-leaf">{editId ? 'Ubah catatan' : 'Catatan baru'}</p><h1 className="mt-1 text-3xl font-bold tracking-tight">{editId ? 'Ubah catatan event' : 'Catat event baru'}</h1><p className="mt-2 text-sm text-slate-500">Simpan informasi dan peluang dari setiap pertemuan.</p></div>{status && <Card className="mb-5 flex items-start gap-3 border-red-200 bg-red-50 p-4 text-sm text-red-700 shadow-none"><AlertCircle className="mt-0.5 shrink-0" size={17}/><p>{status}</p></Card>}{loadingEdit ? <div className="space-y-4">{[1,2,3].map(item => <div key={item} className="h-40 rounded-2xl skeleton-shimmer"/>)}</div> : <form noValidate onSubmit={handleSubmit(submit, invalid)} className="space-y-5"><Card className="p-4 sm:p-6"><h2 className="mb-4 text-lg font-bold">01 · Informasi event</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Nama event" error={errors.name?.message}><Input {...register('name')} placeholder="Contoh: Indonesia Expo"/></Field><Field label="Tanggal" error={errors.date?.message}><DatePicker control={control} name="date"/></Field><Field label="Lokasi" error={errors.location?.message}><Input {...register('location')} placeholder="Jakarta Convention Center"/></Field><Field label="Penyelenggara"><Input {...register('organizer')} placeholder="Nama penyelenggara"/></Field><Field label="Tipe event"><Input {...register('type')} placeholder="Expo, konferensi, seminar..."/></Field></div></Card>
  <Card className="p-4 sm:p-6"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-lg font-bold">02 · Kontak</h2><p className="mt-1 text-sm text-slate-500">Orang yang Anda temui.</p></div><Button type="button" onClick={() => people.append({ ...blankPerson })} className="shrink-0 bg-lime px-3 text-ink"><Plus size={17}/> Tambah kontak</Button></div><div className="space-y-3">{people.fields.map((f, i) => <Collapsible key={f.id} index={i} title={f.name || `Kontak ${i + 1}`} forceOpenSignal={expandSignal} onRemove={() => people.remove(i)}><div className="grid gap-4 sm:grid-cols-2"><Field label="Nama" error={errors.networking?.[i]?.name?.message}><Input {...register(`networking.${i}.name`)} placeholder="Nama lengkap"/></Field><Field label="Perusahaan"><Input {...register(`networking.${i}.company`)} placeholder="Nama perusahaan"/></Field><Field label="Jabatan"><Input {...register(`networking.${i}.position`)} placeholder="Jabatan"/></Field><Field label="Kontak"><Input {...register(`networking.${i}.contact`)} placeholder="WhatsApp / email"/></Field><Field label="Media sosial"><Input {...register(`networking.${i}.social`)} placeholder="LinkedIn / Instagram"/></Field><Field label="Potensi"><NativeSelect {...register(`networking.${i}.potential`)}><option value="">Pilih potensi</option><option value="High">Tinggi</option><option value="Medium">Sedang</option><option value="Low">Rendah</option></NativeSelect></Field></div><Field label="Ringkasan percakapan"><Textarea {...register(`networking.${i}.chatSummary`)} rows={3} placeholder="Topik yang dibahas..."/></Field><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" className="h-5 w-5 accent-leaf" {...register(`networking.${i}.followUp`)} /> Perlu follow-up</label></Collapsible>)}</div>{people.fields.length === 0 && <p className="rounded-xl bg-mist p-4 text-center text-sm text-slate-500">Belum ada kontak. Tambahkan orang yang Anda temui.</p>}</Card>
  <Card className="p-4 sm:p-6"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-lg font-bold">03 · Prospek</h2><p className="mt-1 text-sm text-slate-500">Peluang bisnis yang teridentifikasi.</p></div><Button type="button" onClick={() => prospectItems.append({ ...blankProspect })} className="shrink-0 bg-lime px-3 text-ink"><Plus size={17}/> Tambah prospek</Button></div><div className="space-y-3">{prospectItems.fields.map((f, i) => <Collapsible key={f.id} index={i} title={f.companyName || `Prospek ${i + 1}`} forceOpenSignal={expandSignal} onRemove={() => prospectItems.remove(i)}><div className="grid gap-4 sm:grid-cols-2"><Field label="Nama perusahaan" error={errors.prospects?.[i]?.companyName?.message}><Input {...register(`prospects.${i}.companyName`)} placeholder="Nama perusahaan"/></Field><Field label="Industri"><Input {...register(`prospects.${i}.industry`)} placeholder="Industri"/></Field><Field label="Orang yang ditemui"><Input {...register(`prospects.${i}.personMet`)} placeholder="Nama PIC"/></Field></div><Field label="Ringkasan potensi"><Textarea {...register(`prospects.${i}.potentialSummary`)} rows={3}/></Field><Field label="Catatan"><Textarea {...register(`prospects.${i}.notes`)} rows={3}/></Field></Collapsible>)}</div></Card>
  <Card className="p-4 sm:p-6"><h2 className="mb-4 text-lg font-bold">04 · Tindak lanjut</h2><div className="grid gap-1 sm:grid-cols-2">{actionOptions.map(action => <label key={action.value} className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" value={action.value} className="h-5 w-5 accent-leaf" {...register('nextActions')}/>{action.label}</label>)}</div><div className="mt-5"><Field label="Catatan umum"><Textarea {...register('generalNotes')} rows={5} placeholder="Catatan umum, pengamatan, atau hal penting lainnya..."/></Field></div></Card><div className="fixed inset-x-0 bottom-[calc(76px+env(safe-area-inset-bottom))] z-30 border-t border-line bg-white/95 p-3 backdrop-blur sm:static sm:border-0 sm:bg-transparent sm:p-0"><div className="mx-auto max-w-3xl"><Button disabled={isSubmitting} type="submit" className="w-full bg-ink text-white shadow-lg"><Save size={17}/> {isSubmitting ? 'Menyimpan...' : editId ? 'Simpan Perubahan' : 'Simpan Catatan'}</Button></div></div></form>}</main></Protected>; }
